package com.SpringCrud.entity;
// Generated Jul 19, 2018 3:12:50 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;

	public Emp() {
	}

	public Emp(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
