package com.SpringCrud.entity;
// Generated Jul 19, 2018 3:12:50 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Login generated by hbm2java
 */
public class Login implements java.io.Serializable {

	private long id;
	private String password;
	private String username;

	public Login() {
	}

	public Login(long id) {
		this.id = id;
	}

	public Login(long id, String password, String username) {
		this.id = id;
		this.password = password;
		this.username = username;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
